FROM python:3.14.1-slim-bookworm

WORKDIR /yolov5-snap-go

COPY ./requirements.txt .

# OpenCV dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch torchvision --index-url https://download.pytorch.org/whl/cpu

RUN pip install --no-cache-dir -r requirements.txt

COPY ./ .

CMD [ "python", "main.py" ]

EXPOSE 8000
