# syntax=docker/dockerfile:1.7

FROM node:lts-alpine3.23 AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN corepack enable

FROM base AS deps
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    pnpm install --frozen-lockfile

FROM deps AS build
COPY . .
# Using a dummy env to run Prisma Generate
RUN DATABASE_URL="mysql://build:3306/build" pnpm run prisma:generate
RUN pnpm run build
RUN pnpm prune --prod

FROM node:lts-alpine3.23 AS runtime
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup -S app && adduser -S app -G app

COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist

USER app
EXPOSE 3000
CMD ["node", "dist/index.js"]
